name: Deploy Login-User Lambda Function

on:
    push:
        branches: [ main ]
        paths:
            - 'Login-User/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Login-User
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - run: npm ci
            - run: zip -r function.zip index.js package.json node_modules/ utils/
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
            - run: aws lambda update-function-code --function-name Login-User --zip-file fileb://function.zip